// new-loan-angular/src/app/components/risk-analysis-filters/risk-analysis-filters.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { InputComponent } from '../ui/input/input.component';
import { SelectComponent, SelectOption } from '../ui/select/select.component';
import { DateRangePickerComponent } from '../date-range-picker/date-range-picker.component';
import { DateRange } from '../date-range-picker/date-range-picker.component';

@Component({
  selector: 'app-risk-analysis-filters',
  standalone: true,
  imports: [CommonModule, FormsModule, InputComponent, SelectComponent, DateRangePickerComponent],
  template: `
    <div>
      <h2 class="mb-1 text-xl font-semibold text-card-foreground">
        Risk Analysis Filters
      </h2>
      <p class="mb-5 text-base text-muted-foreground">
        Filter and sort loans by various criteria
      </p>

      <div class="flex flex-col gap-4">
        <!-- Search Input -->
        <div class="relative w-full">
          <svg class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
            <app-input
              type="text"
              placeholder="Search by borrower, loan ID, or property..."
              [value]="searchQuery"
              (valueChange)="searchChange.emit($event)"
              className="h-12 pl-11 text-base"
            ></app-input>
        </div>

        <div class="flex flex-wrap items-center gap-4">
          <!-- Risk Score Filter -->
          <app-select
            [options]="riskScoreOptions"
            [value]="riskScoreFilter"
            (valueChange)="handleRiskScoreChange($event)"
            placeholder="Risk Score"
            className="h-12 w-[150px] text-base"
          ></app-select>

          <!-- TLR Status Filter -->
          <app-select
            [options]="tlrStatusOptions"
            [value]="tlrStatusFilter"
            (valueChange)="handleTlrStatusChange($event)"
            placeholder="TLR Status"
            className="h-12 w-[180px] text-base"
          ></app-select>

          <!-- Credit Delegation Type Filter -->
          <app-select
            [options]="delegationOptions"
            [value]="delegationFilter"
            (valueChange)="handleDelegationChange($event)"
            placeholder="Delegation Type"
            className="h-12 w-[180px] text-base"
          ></app-select>

          <!-- Lender Filter -->
          <app-select
            [options]="lenderOptions"
            [value]="lenderFilter"
            (valueChange)="handleLenderChange($event)"
            placeholder="All Lenders"
            className="h-12 w-[180px] text-base"
          ></app-select>

          <!-- Acquisition Date Range Filter -->
          <app-date-range-picker
            [value]="acquisitionDateRange"
            (valueChange)="handleAcquisitionDateRangeChange($event)"
            label="Acquisition Date"
          ></app-date-range-picker>

          <!-- Commitment Date Range Filter -->
          <app-date-range-picker
            [value]="commitmentDateRange"
            (valueChange)="handleCommitmentDateRangeChange($event)"
            label="Commitment Date"
          ></app-date-range-picker>

          <!-- Underwriter Filter -->
          <app-select
            [options]="underwriterOptions"
            [value]="underwriterFilter"
            (valueChange)="handleUnderwriterChange($event)"
            placeholder="Underwriter"
            className="h-12 w-[170px] text-base"
          ></app-select>

          <!-- Originator Filter -->
          <app-select
            [options]="originatorOptions"
            [value]="originatorFilter"
            (valueChange)="handleOriginatorChange($event)"
            placeholder="Originator"
            className="h-12 w-[170px] text-base"
          ></app-select>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class RiskAnalysisFiltersComponent {
  @Input() searchQuery: string = '';
  @Output() searchChange = new EventEmitter<string>();
  @Input() riskScoreFilter: string = 'all';
  @Output() riskScoreChange = new EventEmitter<string>();
  @Input() tlrStatusFilter: string = 'all';
  @Output() tlrStatusChange = new EventEmitter<string>();
  @Input() delegationFilter: string = 'all';
  @Output() delegationChange = new EventEmitter<string>();
  @Input() lenderFilter: string = 'all';
  @Output() lenderChange = new EventEmitter<string>();
  @Input() acquisitionDateRange: DateRange = { startDate: 'all', endDate: '2025-03' };
  @Output() acquisitionDateRangeChange = new EventEmitter<DateRange>();
  @Input() commitmentDateRange: DateRange = { startDate: 'all', endDate: '2025-03' };
  @Output() commitmentDateRangeChange = new EventEmitter<DateRange>();
  @Input() underwriterFilter: string = 'all';
  @Output() underwriterChange = new EventEmitter<string>();
  @Input() originatorFilter: string = 'all';
  @Output() originatorChange = new EventEmitter<string>();

  riskScoreOptions: SelectOption[] = [
    { value: 'all', label: 'All Risk Scores' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
  ];

  tlrStatusOptions: SelectOption[] = [
    { value: 'all', label: 'All TLR Status' },
    { value: 'TLR Completed', label: 'TLR Completed' },
    { value: 'TLR Not Completed', label: 'TLR Not Completed' },
    { value: 'unknown', label: 'Unknown' },
  ];

  delegationOptions: SelectOption[] = [
    { value: 'all', label: 'All Delegation' },
    { value: 'Preview', label: 'Preview' },
    { value: 'PD', label: 'PD (Performance)' },
    { value: 'Standard', label: 'Standard' },
  ];

  lenderOptions: SelectOption[] = [
    { value: 'all', label: 'All Lenders' },
    { value: 'Lender A', label: 'Lender A' },
    { value: 'First National', label: 'First National' },
    { value: 'Capital Bank', label: 'Capital Bank' },
  ];

  underwriterOptions: SelectOption[] = [
    { value: 'all', label: 'All Underwriters' },
    { value: 'John Smith', label: 'John Smith' },
    { value: 'Michael Chen', label: 'Michael Chen' },
    { value: 'David Wilson', label: 'David Wilson' },
    { value: 'Emily Davis', label: 'Emily Davis' },
    { value: 'Jennifer Taylor', label: 'Jennifer Taylor' },
    { value: 'Chris Thompson', label: 'Chris Thompson' },
  ];

  originatorOptions: SelectOption[] = [
    { value: 'all', label: 'All Originators' },
    { value: 'Sarah Johnson', label: 'Sarah Johnson' },
    { value: 'Lisa Park', label: 'Lisa Park' },
    { value: 'Amanda Brown', label: 'Amanda Brown' },
    { value: 'Robert Martinez', label: 'Robert Martinez' },
    { value: 'Kevin Anderson', label: 'Kevin Anderson' },
    { value: 'Michelle Lee', label: 'Michelle Lee' },
  ];

  // Helper methods to handle value changes with proper typing
  handleRiskScoreChange(value: string) {
    this.riskScoreChange.emit(value);
  }

  handleTlrStatusChange(value: string) {
    this.tlrStatusChange.emit(value);
  }

  handleDelegationChange(value: string) {
    this.delegationChange.emit(value);
  }

  handleLenderChange(value: string) {
    this.lenderChange.emit(value);
  }

  handleUnderwriterChange(value: string) {
    this.underwriterChange.emit(value);
  }

  handleOriginatorChange(value: string) {
    this.originatorChange.emit(value);
  }

  handleAcquisitionDateRangeChange(value: DateRange) {
    this.acquisitionDateRangeChange.emit(value);
  }

  handleCommitmentDateRangeChange(value: DateRange) {
    this.commitmentDateRangeChange.emit(value);
  }

  // Expose event emitters with correct names for template binding
  get onSearchChange() { return this.searchChange; }
  get onRiskScoreChange() { return this.riskScoreChange; }
  get onTlrStatusChange() { return this.tlrStatusChange; }
  get onDelegationChange() { return this.delegationChange; }
  get onLenderChange() { return this.lenderChange; }
  get onAcquisitionDateRangeChange() { return this.acquisitionDateRangeChange; }
  get onCommitmentDateRangeChange() { return this.commitmentDateRangeChange; }
  get onUnderwriterChange() { return this.underwriterChange; }
  get onOriginatorChange() { return this.originatorChange; }
}

// new-loan/components/risk-analysis-filters.tsx
"use client";

import { Search } from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { DateRangePicker, type DateRange } from "@/components/date-range-picker";

export type { DateRange };

interface RiskAnalysisFiltersProps {
  searchQuery: string;
  onSearchChange: (value: string) => void;
  riskScoreFilter: string;
  onRiskScoreChange: (value: string) => void;
  tlrStatusFilter: string;
  onTlrStatusChange: (value: string) => void;
  delegationFilter: string;
  onDelegationChange: (value: string) => void;
  lenderFilter: string;
  onLenderChange: (value: string) => void;
  acquisitionDateRange: DateRange;
  onAcquisitionDateRangeChange: (range: DateRange) => void;
  commitmentDateRange: DateRange;
  onCommitmentDateRangeChange: (range: DateRange) => void;
  underwriterFilter: string;
  onUnderwriterChange: (value: string) => void;
  originatorFilter: string;
  onOriginatorChange: (value: string) => void;
}

export function RiskAnalysisFilters({
  searchQuery,
  onSearchChange,
  riskScoreFilter,
  onRiskScoreChange,
  tlrStatusFilter,
  onTlrStatusChange,
  delegationFilter,
  onDelegationChange,
  lenderFilter,
  onLenderChange,
  acquisitionDateRange,
  onAcquisitionDateRangeChange,
  commitmentDateRange,
  onCommitmentDateRangeChange,
  underwriterFilter,
  onUnderwriterChange,
  originatorFilter,
  onOriginatorChange,
}: RiskAnalysisFiltersProps) {
  return (
    <div>
      <h2 className="mb-1 text-xl font-semibold text-card-foreground">
        Risk Analysis Filters
      </h2>
      <p className="mb-5 text-base text-muted-foreground">
        Filter and sort loans by various criteria
      </p>

      <div className="flex flex-col gap-4">
        {/* Search Input (always above other controls) */}
        <div className="relative w-full">
          <Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
          <Input
            type="text"
            placeholder="Search by borrower, loan ID, or property..."
            value={searchQuery}
            onChange={(e) => onSearchChange(e.target.value)}
            className="h-12 pl-11 text-base"
          />
        </div>

        <div className="flex flex-wrap items-center gap-4">
        {/* Risk Score Filter */}
        <Select value={riskScoreFilter} onValueChange={onRiskScoreChange}>
          <SelectTrigger className="h-12 w-[150px] text-base">
            <SelectValue placeholder="Risk Score" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All Risk Scores</SelectItem>
            <SelectItem value="1" className="text-base">1</SelectItem>
            <SelectItem value="2" className="text-base">2</SelectItem>
            <SelectItem value="3" className="text-base">3</SelectItem>
            <SelectItem value="4" className="text-base">4</SelectItem>
          </SelectContent>
        </Select>

        {/* TLR Status Filter */}
        <Select value={tlrStatusFilter} onValueChange={onTlrStatusChange}>
          <SelectTrigger className="h-12 w-[180px] text-base">
            <SelectValue placeholder="TLR Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All TLR Status</SelectItem>
            <SelectItem value="TLR Completed" className="text-base">TLR Completed</SelectItem>
            <SelectItem value="TLR Not Completed" className="text-base">TLR Not Completed</SelectItem>
            <SelectItem value="unknown" className="text-base">Unknown</SelectItem>
          </SelectContent>
        </Select>

        {/* Credit Delegation Type Filter */}
        <Select value={delegationFilter} onValueChange={onDelegationChange}>
          <SelectTrigger className="h-12 w-[180px] text-base">
            <SelectValue placeholder="Delegation Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All Delegation</SelectItem>
            <SelectItem value="Preview" className="text-base">Preview</SelectItem>
            <SelectItem value="PD" className="text-base">PD (Performance)</SelectItem>
            <SelectItem value="Standard" className="text-base">Standard</SelectItem>
          </SelectContent>
        </Select>

        {/* Lender Filter */}
        <Select value={lenderFilter} onValueChange={onLenderChange}>
          <SelectTrigger className="h-12 w-[180px] text-base">
            <SelectValue placeholder="All Lenders" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All Lenders</SelectItem>
            <SelectItem value="Lender A" className="text-base">Lender A</SelectItem>
            <SelectItem value="First National" className="text-base">First National</SelectItem>
            <SelectItem value="Capital Bank" className="text-base">Capital Bank</SelectItem>
          </SelectContent>
        </Select>

        {/* Acquisition Date Range Filter */}
        <DateRangePicker value={acquisitionDateRange} onChange={onAcquisitionDateRangeChange} label="Acquisition Date" />

        {/* Commitment Date Range Filter */}
        <DateRangePicker value={commitmentDateRange} onChange={onCommitmentDateRangeChange} label="Commitment Date" />

        {/* Underwriter Filter */}
        <Select value={underwriterFilter} onValueChange={onUnderwriterChange}>
          <SelectTrigger className="h-12 w-[170px] text-base">
            <SelectValue placeholder="Underwriter" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All Underwriters</SelectItem>
            <SelectItem value="John Smith" className="text-base">John Smith</SelectItem>
            <SelectItem value="Michael Chen" className="text-base">Michael Chen</SelectItem>
            <SelectItem value="David Wilson" className="text-base">David Wilson</SelectItem>
            <SelectItem value="Emily Davis" className="text-base">Emily Davis</SelectItem>
            <SelectItem value="Jennifer Taylor" className="text-base">Jennifer Taylor</SelectItem>
            <SelectItem value="Chris Thompson" className="text-base">Chris Thompson</SelectItem>
          </SelectContent>
        </Select>

        {/* Originator Filter */}
        <Select value={originatorFilter} onValueChange={onOriginatorChange}>
          <SelectTrigger className="h-12 w-[170px] text-base">
            <SelectValue placeholder="Originator" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-base">All Originators</SelectItem>
            <SelectItem value="Sarah Johnson" className="text-base">Sarah Johnson</SelectItem>
            <SelectItem value="Lisa Park" className="text-base">Lisa Park</SelectItem>
            <SelectItem value="Amanda Brown" className="text-base">Amanda Brown</SelectItem>
            <SelectItem value="Robert Martinez" className="text-base">Robert Martinez</SelectItem>
            <SelectItem value="Kevin Anderson" className="text-base">Kevin Anderson</SelectItem>
            <SelectItem value="Michelle Lee" className="text-base">Michelle Lee</SelectItem>
          </SelectContent>
        </Select>

        
        </div>
      </div>
    </div>
  );
}
